### ISSUE TITLE
Obsolete code

### ISSUE THREAD

**Issue by LoneStar1994** [elixir-examples/elixir-examples.github.io#11]
Hello!
I was taking a look at the codes in the next link:    [  https://elixir-examples.github.io   ]

And I realized that some of them are obolsete. For example: 

https://elixir-examples.github.io/examples/strip-trim-leading-and-trailing-whitespace-from-a-string

saids : 

"a" = String.strip("    a     ")   

And it should be 

"a" = String.trim("    a   ")

Im using elixir 1.5.2

Regards! If I happen to find more I'll tell you, thank you

**Comment by bjfish** [comment]
Thanks for reporting this. It is now fixed:
https://elixir-examples.github.io/examples/strip-trim-leading-and-trailing-whitespace-from-a-string
